global:
  scrape_interval:     5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'balancer'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'backend-1-main'
    static_configs:
      - targets: ['185.241.192.11:5000/metrics']

  - job_name: 'backend-1-metrics'
    static_configs:
      - targets: ['185.241.192.11:9100']

  - job_name:  'backend-2-main'
    static_configs:
      - targets: ['185.241.195.151:5000/metrics']

  - job_name: 'backend-2-metrics'
    static_configs:
      - targets: ['185.241.195.151:9100']

  - job_name:  'backend-3-main'
    static_configs:
      - targets: ['185.241.195.174:5000/metrics']

  - job_name: 'backend-3-metrics'
    static_configs:
      - targets: ['185.241.195.174:9100']