// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package models

import (
	json "encoding/json"
	fmt "fmt"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson68762faaDecodeRSOIInternalModels(in *jlexer.Lexer, out *PersonaResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	var IDSet bool
	var NameSet bool
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint(in.Uint())
			IDSet = true
		case "name":
			out.Name = string(in.String())
			NameSet = true
		case "age":
			out.Age = uint(in.Uint())
		case "address":
			out.Address = string(in.String())
		case "work":
			out.Work = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
	if !IDSet {
		in.AddError(fmt.Errorf("key 'id' is required"))
	}
	if !NameSet {
		in.AddError(fmt.Errorf("key 'name' is required"))
	}
}
func easyjson68762faaEncodeRSOIInternalModels(out *jwriter.Writer, in PersonaResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"id\":"
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		out.RawString(prefix)
		out.String(string(in.Name))
	}
	if in.Age != 0 {
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Uint(uint(in.Age))
	}
	if in.Address != "" {
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	if in.Work != "" {
		const prefix string = ",\"work\":"
		out.RawString(prefix)
		out.String(string(in.Work))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PersonaResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson68762faaEncodeRSOIInternalModels(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PersonaResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson68762faaEncodeRSOIInternalModels(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PersonaResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson68762faaDecodeRSOIInternalModels(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PersonaResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson68762faaDecodeRSOIInternalModels(l, v)
}
func easyjson68762faaDecodeRSOIInternalModels1(in *jlexer.Lexer, out *PersonaRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "id":
			out.ID = uint(in.Uint())
		case "name":
			out.Name = string(in.String())
		case "age":
			out.Age = uint(in.Uint())
		case "address":
			out.Address = string(in.String())
		case "work":
			out.Work = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson68762faaEncodeRSOIInternalModels1(out *jwriter.Writer, in PersonaRequest) {
	out.RawByte('{')
	first := true
	_ = first
	if in.ID != 0 {
		const prefix string = ",\"id\":"
		first = false
		out.RawString(prefix[1:])
		out.Uint(uint(in.ID))
	}
	{
		const prefix string = ",\"name\":"
		if first {
			first = false
			out.RawString(prefix[1:])
		} else {
			out.RawString(prefix)
		}
		out.String(string(in.Name))
	}
	if in.Age != 0 {
		const prefix string = ",\"age\":"
		out.RawString(prefix)
		out.Uint(uint(in.Age))
	}
	if in.Address != "" {
		const prefix string = ",\"address\":"
		out.RawString(prefix)
		out.String(string(in.Address))
	}
	if in.Work != "" {
		const prefix string = ",\"work\":"
		out.RawString(prefix)
		out.String(string(in.Work))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v PersonaRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson68762faaEncodeRSOIInternalModels1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v PersonaRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson68762faaEncodeRSOIInternalModels1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *PersonaRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson68762faaDecodeRSOIInternalModels1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *PersonaRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson68762faaDecodeRSOIInternalModels1(l, v)
}
